server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/urlstat
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  file:
    name: logs/loging.log
